codecov:
  branch: main
comment:
  behavior: default
  require_changes: true
coverage:
  range: 66..95
  round: down
  precision: 2
  status:
    changes: false
    project:
      default:
        target: 66.0
        threshold: 0.5
    patch:
      default:
        target: 80.0
