//! The `show_diff` and `analyze_diff` commands.
//!
//! Ports upstream `mtui.commands.showdiff`. A `source.diff` generated by OBS/osc
//! is a concatenation of `header:` / `-----` delimited sections (`changes
//! files:`, `old:`, `new:`, `spec files:`, repeated `other changes:`), *not* a
//! plain unified diff, so it is parsed section by section. `show_diff` pages the
//! raw file; `analyze_diff` cross-checks patch definitions vs application and
//! surfaces review-relevant references.

use std::collections::BTreeSet;

use async_trait::async_trait;
use clap::ArgMatches;
use regex::Regex;
use std::sync::LazyLock;

use super::support::{complete_with_templates, page_output};
use crate::command::{Command, Scope};
use crate::error::{CommandError, CommandResult};
use crate::session::Session;

// Section framing.
static SECTION_HEADER: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^([a-z][a-z0-9 ._-]*):\s*$").unwrap());
static SECTION_UNDERLINE: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"^-{3,}\s*$").unwrap());
// `+Patch13:        some-fix.patch` style definitions in a spec file.
static PATCH_DEF: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^([+-])Patch(\d*):\s+(.*\.patch)\s*$").unwrap());
// `+%patch13 -p1` style application in a spec file.
static PATCH_APPLY: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"^[+-]%patch(\d*)\b").unwrap());
// `%autosetup` / `%autopatch` apply patches implicitly.
static AUTOMACRO: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^[+-]?\s*%auto(?:setup|patch)\b").unwrap());
// Source tarball / archive names in `old:` / `new:` sections.
static ARCHIVE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"\.(?:tar(?:\.\w+)?|tgz|tbz2?|txz|zip|obscpio)\s*$").unwrap());
// Reviewer-relevant references from changelog text.
static REFERENCE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"\b(?:CVE-\d{4}-\d+|b(?:sc|oo|nc)#\d+|jsc#\w+-\d+)\b").unwrap());
// Version / global macro bumps worth surfacing. Ported verbatim from upstream
// `_VERSION_BUMP`, including its quirk: the trailing `\b` sits after `Version:`
// (a non-word `:` followed by whitespace is not a word boundary), so plain
// `+Version:` lines never actually match — only the `%define`/`%global …ver…`
// macro branch does. Preserved for behavioural parity rather than "fixed".
static VERSION_BUMP: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)^[+-]\s*(?:Version:|%(?:define|global)\s+\S*ver\w*)\b").unwrap()
});

/// A parsed `(header, body_lines)` section of a `source.diff`.
type Section = (String, Vec<String>);

/// Splits a `source.diff` into `(header, body)` sections (upstream
/// `_split_sections`). A section starts with a `header:` line immediately
/// followed by a `-----` underline; preamble before the first header is returned
/// under an empty header.
fn split_sections(text: &str) -> Vec<Section> {
    let lines: Vec<&str> = text.split('\n').collect();
    let mut sections: Vec<Section> = Vec::new();
    let mut header = String::new();
    let mut body: Vec<String> = Vec::new();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        if let Some(cap) = SECTION_HEADER.captures(line)
            && i + 1 < lines.len()
            && SECTION_UNDERLINE.is_match(lines[i + 1])
        {
            sections.push((std::mem::take(&mut header), std::mem::take(&mut body)));
            header = cap[1].to_owned();
            i += 2;
            continue;
        }
        body.push(line.to_owned());
        i += 1;
    }
    sections.push((header, body));
    sections
}

/// Every body whose header matches `name` (sections may repeat).
fn section_bodies<'a>(sections: &'a [Section], name: &str) -> Vec<&'a [String]> {
    sections
        .iter()
        .filter(|(h, _)| h == name)
        .map(|(_, b)| b.as_slice())
        .collect()
}

/// The flattened lines of every `spec files` body.
fn flatten<'a>(sections: &'a [Section], name: &str) -> Vec<&'a String> {
    section_bodies(sections, name)
        .into_iter()
        .flat_map(<[String]>::iter)
        .collect()
}

/// Parses `(added, removed)` patch definitions from spec lines (upstream
/// `_defined_patches`). `added` is `(number, filename)`; `removed` is filenames.
fn defined_patches(spec_lines: &[&String]) -> (Vec<(String, String)>, Vec<String>) {
    let mut added = Vec::new();
    let mut removed = Vec::new();
    for line in spec_lines {
        if let Some(cap) = PATCH_DEF.captures(line) {
            let sign = &cap[1];
            let number = cap[2].to_owned();
            let filename = cap[3].trim().to_owned();
            if sign == "+" {
                added.push((number, filename));
            } else {
                removed.push(filename);
            }
        }
    }
    (added, removed)
}

/// Inspects how patches are applied (upstream `_apply_info`): returns
/// `(applied_numbers, uses_automacro)`. `uses_automacro` is true when
/// `%autosetup`/`%autopatch` is present or no `%patch` lines exist at all.
fn apply_info(spec_lines: &[&String]) -> (BTreeSet<String>, bool) {
    let mut applied = BTreeSet::new();
    let mut uses_automacro = false;
    let mut saw_patch_line = false;
    for line in spec_lines {
        if AUTOMACRO.is_match(line) {
            uses_automacro = true;
        }
        if let Some(cap) = PATCH_APPLY.captures(line) {
            saw_patch_line = true;
            applied.insert(cap[1].to_owned());
        }
    }
    if !saw_patch_line {
        uses_automacro = true;
    }
    (applied, uses_automacro)
}

/// Unique archive filenames from `old:`/`new:` bodies (upstream `_archives`).
fn archives(bodies: &[&[String]]) -> Vec<String> {
    let mut names: Vec<String> = Vec::new();
    for body in bodies {
        for line in body.iter() {
            let candidate = line.trim().trim_start_matches(['+', '-']).trim().to_owned();
            if !candidate.is_empty() && ARCHIVE.is_match(&candidate) && !names.contains(&candidate)
            {
                names.push(candidate);
            }
        }
    }
    names
}

/// Reads the loaded report's `source.diff`, or a clear error if unavailable.
fn read_source_diff(session: &Session) -> Result<String, CommandError> {
    let wd = session
        .metadata()
        .base()
        .report_wd()
        .map_err(|e| CommandError::Other(format!("no report loaded: {e}")))?;
    let path = wd.join("source.diff");
    std::fs::read_to_string(&path)
        .map_err(|e| CommandError::Other(format!("{}: {e}", path.display())))
}

/// Shows the raw OBS source diff.
pub struct ShowDiff;

#[async_trait]
impl Command for ShowDiff {
    fn name(&self) -> &'static str {
        "show_diff"
    }

    fn about(&self) -> Option<&'static str> {
        Some("Shows the raw OBS source diff.")
    }

    fn scope(&self) -> Scope {
        Scope::Fanout
    }

    fn complete(&self, session: &Session, text: &str, line: &str) -> Vec<String> {
        complete_with_templates(session, &[], Vec::new(), line, text)
    }

    async fn call(&self, session: &mut Session, _args: &ArgMatches) -> CommandResult {
        let text = read_source_diff(session)?;
        let lines: Vec<String> = text.split('\n').map(str::to_owned).collect();
        page_output(session, &lines).await;
        Ok(())
    }
}

/// Analyzes the OBS source diff to assist code review.
pub struct AnalyzeDiff;

#[async_trait]
impl Command for AnalyzeDiff {
    fn name(&self) -> &'static str {
        "analyze_diff"
    }

    fn about(&self) -> Option<&'static str> {
        Some("Analyzes the OBS source diff to assist code review.")
    }

    fn scope(&self) -> Scope {
        Scope::Fanout
    }

    async fn call(&self, session: &mut Session, _args: &ArgMatches) -> CommandResult {
        let text = read_source_diff(session)?;
        let sections = split_sections(&text);

        let spec_lines = flatten(&sections, "spec files");
        if spec_lines.is_empty() {
            session.display.println("No spec mentioned in source.diff");
            return Ok(());
        }

        let changes_text = flatten(&sections, "changes files")
            .iter()
            .map(|s| s.as_str())
            .collect::<Vec<_>>()
            .join("\n");

        let (added_patches, removed_patches) = defined_patches(&spec_lines);
        let (applied, uses_automacro) = apply_info(&spec_lines);

        if !uses_automacro {
            let defined: BTreeSet<String> = added_patches.iter().map(|(n, _)| n.clone()).collect();
            if defined != applied {
                tracing::warn!(
                    defined = ?defined, applied = ?applied,
                    "patch numbers defined in the spec file do not match applied patches"
                );
            }
        }

        // Which added patches are referenced in the changelog?
        let mut mentioned: Vec<String> = Vec::new();
        for (_, filename) in &added_patches {
            if changes_text.contains(filename.as_str()) {
                mentioned.push(filename.clone());
            } else {
                tracing::warn!(patch = %filename, "patch isn't mentioned in any changelog");
            }
        }

        self.print_report(
            session,
            &sections,
            &added_patches,
            &removed_patches,
            &mentioned,
            uses_automacro,
            &changes_text,
        );
        Ok(())
    }
}

impl AnalyzeDiff {
    #[allow(clippy::too_many_arguments)]
    fn print_report(
        &self,
        session: &mut Session,
        sections: &[Section],
        added_patches: &[(String, String)],
        removed_patches: &[String],
        mentioned: &[String],
        uses_automacro: bool,
        changes_text: &str,
    ) {
        let d = &mut session.display;
        d.println("Source diff analysis:");
        d.println("");

        let old_archives = archives(&section_bodies(sections, "old"));
        let new_archives = archives(&section_bodies(sections, "new"));
        if !old_archives.is_empty() || !new_archives.is_empty() {
            d.println("  Source archives:");
            for name in &old_archives {
                d.println(&format!("    - {name}"));
            }
            for name in &new_archives {
                d.println(&format!("    + {name}"));
            }
            d.println("");
        }

        d.println("  Patches added in spec file:");
        if added_patches.is_empty() {
            d.println("    (none)");
        } else {
            for (i, (_, filename)) in added_patches.iter().enumerate() {
                let marker = if mentioned.contains(filename) {
                    ""
                } else {
                    "  (not in changelog)"
                };
                d.println(&format!("    {i} - {filename}{marker}"));
            }
        }
        d.println("");

        if !removed_patches.is_empty() {
            d.println("  Patches removed from spec file:");
            for (i, filename) in removed_patches.iter().enumerate() {
                d.println(&format!("    {i} - {filename}"));
            }
            d.println("");
        }

        if uses_automacro {
            d.println("  Patch application: %autosetup/%autopatch (apply check skipped)");
            d.println("");
        }

        let bumps: BTreeSet<String> = flatten(sections, "spec files")
            .iter()
            .filter(|l| VERSION_BUMP.is_match(l))
            .map(|l| l.trim().to_owned())
            .collect();
        if !bumps.is_empty() {
            d.println("  Version / macro changes:");
            for line in &bumps {
                d.println(&format!("    {line}"));
            }
            d.println("");
        }

        let references: BTreeSet<String> = REFERENCE
            .find_iter(changes_text)
            .map(|m| m.as_str().to_owned())
            .collect();
        if !references.is_empty() {
            d.println("  References in changelog:");
            d.println(&format!(
                "    {}",
                references.into_iter().collect::<Vec<_>>().join(", ")
            ));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::testkit::{empty_session, matches, session_with_hosts};

    #[test]
    fn names_and_scopes() {
        assert_eq!(ShowDiff.name(), "show_diff");
        assert_eq!(ShowDiff.scope(), Scope::Fanout);
        assert_eq!(AnalyzeDiff.name(), "analyze_diff");
        assert_eq!(AnalyzeDiff.scope(), Scope::Fanout);
    }

    #[test]
    fn show_diff_complete_offers_templates_no_hosts() {
        let (session, _buf) = session_with_hosts("SUSE:Maintenance:1:1", &["h1"], "ok");
        let out = ShowDiff.complete(&session, "", "show_diff ");
        assert!(out.contains(&"-T".to_owned()), "{out:?}");
        assert!(out.contains(&"SUSE:Maintenance:1:1".to_owned()), "{out:?}");
        assert!(!out.contains(&"h1".to_owned()), "{out:?}");
    }

    #[test]
    fn split_sections_frames_headers() {
        let text = "preamble\nspec files:\n-----\n+Patch1: fix.patch\nchanges files:\n-----\n- bsc#1 fixed\n";
        let s = split_sections(text);
        assert_eq!(section_bodies(&s, "spec files").len(), 1);
        assert_eq!(section_bodies(&s, "changes files").len(), 1);
    }

    #[test]
    fn defined_and_applied_patches() {
        let lines = [
            "+Patch1:  fix.patch".to_owned(),
            "-Patch2:  old.patch".to_owned(),
            "+%patch1 -p1".to_owned(),
        ];
        let refs: Vec<&String> = lines.iter().collect();
        let (added, removed) = defined_patches(&refs);
        assert_eq!(added, vec![("1".to_owned(), "fix.patch".to_owned())]);
        assert_eq!(removed, vec!["old.patch".to_owned()]);
        let (applied, automacro) = apply_info(&refs);
        assert!(applied.contains("1"));
        assert!(!automacro);
    }

    #[test]
    fn automacro_detected_and_no_patch_lines() {
        let lines = ["+%autosetup -p1".to_owned()];
        let refs: Vec<&String> = lines.iter().collect();
        assert!(apply_info(&refs).1);
        // No %patch and no automacro → still automacro (implicit).
        let empty: Vec<&String> = Vec::new();
        assert!(apply_info(&empty).1);
    }

    #[test]
    fn archives_extracts_tarballs() {
        let body = vec![
            "  + foo-1.2.tar.gz".to_owned(),
            "  not-an-archive".to_owned(),
        ];
        let slices: Vec<&[String]> = vec![body.as_slice()];
        assert_eq!(archives(&slices), vec!["foo-1.2.tar.gz".to_owned()]);
    }

    #[tokio::test]
    async fn show_diff_no_report_errors() {
        let (mut session, _buf) = empty_session();
        let args = matches(&ShowDiff, &[]);
        let err = ShowDiff.call(&mut session, &args).await.unwrap_err();
        assert!(matches!(err, CommandError::Other(_)));
    }

    #[tokio::test]
    async fn analyze_diff_no_report_errors() {
        let (mut session, _buf) = empty_session();
        let args = matches(&AnalyzeDiff, &[]);
        let err = AnalyzeDiff.call(&mut session, &args).await.unwrap_err();
        assert!(matches!(err, CommandError::Other(_)));
    }

    /// Writes `source.diff` into a session's active-report working directory and
    /// returns the session + buffer, so the diff commands read a real file.
    fn session_with_diff(
        diff: &str,
    ) -> (Session, crate::commands::testkit::Buffer, tempfile::TempDir) {
        use crate::commands::testkit::session_with_hosts;
        let (mut session, buf) = session_with_hosts("SUSE:Maintenance:1:1", &["h1"], "ok");
        let dir = tempfile::tempdir().unwrap();
        // report_wd() == parent of `path`; put source.diff beside a "log" file.
        std::fs::write(dir.path().join("source.diff"), diff).unwrap();
        session.metadata_mut().base_mut().path = Some(dir.path().join("log"));
        (session, buf, dir)
    }

    #[tokio::test]
    async fn show_diff_pages_raw_file() {
        let (mut session, buf, _dir) = session_with_diff("line one\nline two\n");
        let args = matches(&ShowDiff, &[]);
        ShowDiff.call(&mut session, &args).await.unwrap();
        let out = buf.contents();
        assert!(out.contains("line one"), "{out}");
        assert!(out.contains("line two"), "{out}");
    }

    #[tokio::test]
    #[serial_test::serial(env)]
    #[allow(unsafe_code)]
    async fn show_diff_interactive_quits_early_on_q() {
        use mtui_hosts::Prompter;

        // Tiny screen (2 rows) + a `q`-answering prompter: paging stops after the
        // first screen, so later lines are not shown. `ACCTEST_*` → `#[serial(env)]`.
        unsafe {
            std::env::set_var("ACCTEST_COLS", "80");
            std::env::set_var("ACCTEST_ROWS", "3");
        }
        let (mut session, buf, _dir) = session_with_diff("first\nsecond\nthird\nfourth\nfifth\n");
        session.is_repl = true;
        session.set_prompter(Prompter::new(std::sync::Arc::new(|_t: String| {
            Box::pin(async move { Ok("q".to_owned()) })
                as std::pin::Pin<
                    Box<dyn std::future::Future<Output = std::io::Result<String>> + Send>,
                >
        })));
        let args = matches(&ShowDiff, &[]);
        ShowDiff.call(&mut session, &args).await.unwrap();
        unsafe {
            std::env::remove_var("ACCTEST_COLS");
            std::env::remove_var("ACCTEST_ROWS");
        }
        let out = buf.contents();
        assert!(out.contains("first") && out.contains("second"), "{out}");
        assert!(!out.contains("fourth"), "should have quit early: {out}");
    }

    #[tokio::test]
    async fn analyze_diff_no_spec_reports_message() {
        let (mut session, buf, _dir) = session_with_diff("preamble only\n");
        let args = matches(&AnalyzeDiff, &[]);
        AnalyzeDiff.call(&mut session, &args).await.unwrap();
        assert!(
            buf.contents().contains("No spec mentioned in source.diff"),
            "{}",
            buf.contents()
        );
    }

    #[tokio::test]
    async fn analyze_diff_full_report() {
        let diff = "\
old:
-----
 foo-1.0.tar.gz
new:
-----
 foo-1.1.tar.gz
spec files:
-----
+Patch1:  fix-cve.patch
+%patch1 -p1
+%global libver 1.1
changes files:
-----
+ - fix-cve.patch resolves CVE-2024-1234 (bsc#1200000)
";
        let (mut session, buf, _dir) = session_with_diff(diff);
        let args = matches(&AnalyzeDiff, &[]);
        AnalyzeDiff.call(&mut session, &args).await.unwrap();
        let out = buf.contents();
        assert!(out.contains("Source diff analysis:"), "{out}");
        assert!(out.contains("Source archives:"), "{out}");
        assert!(out.contains("- foo-1.0.tar.gz"), "{out}");
        assert!(out.contains("+ foo-1.1.tar.gz"), "{out}");
        assert!(out.contains("Patches added in spec file:"), "{out}");
        assert!(out.contains("fix-cve.patch"), "{out}");
        assert!(out.contains("Version / macro changes:"), "{out}");
        assert!(out.contains("References in changelog:"), "{out}");
        assert!(out.contains("CVE-2024-1234"), "{out}");
        assert!(out.contains("bsc#1200000"), "{out}");
    }

    #[tokio::test]
    async fn analyze_diff_removed_and_automacro_and_unmentioned() {
        let diff = "\
spec files:
-----
+Patch2:  new.patch
-Patch3:  gone.patch
+%autosetup -p1
";
        let (mut session, buf, _dir) = session_with_diff(diff);
        let args = matches(&AnalyzeDiff, &[]);
        AnalyzeDiff.call(&mut session, &args).await.unwrap();
        let out = buf.contents();
        assert!(out.contains("Patches removed from spec file:"), "{out}");
        assert!(out.contains("gone.patch"), "{out}");
        assert!(out.contains("%autosetup/%autopatch"), "{out}");
        // new.patch is not in any changelog section.
        assert!(out.contains("(not in changelog)"), "{out}");
    }
}
