"""Inject the ``openqa_overview`` block into a testreport's ``log`` file.

The block lives under the existing ``regression tests:`` section. On
first export the block is appended after any existing content in that
section. On subsequent exports, a previously-inserted block is detected
via the BEGIN/END markers from ``mtui.connector.oqa_search`` and
replaced in place so the file never accumulates duplicate copies.
"""

from __future__ import annotations

from collections.abc import MutableSequence
from logging import getLogger

from ...connector.oqa_search import (
    OVERVIEW_BEGIN_MARKER,
    OVERVIEW_END_MARKER,
    BuildCheckResult,
    GroupResult,
    VersionResult,
    render_overview,
)

logger = getLogger("mtui.export.overview_inject")

# The header line that delimits the section we own (verbatim, with the
# trailing newline that FileList stores).
_REGRESSION_HEADER = "regression tests:\n"
# The next section header in the template. We always keep the inserted
# block strictly before this line.
_NEXT_SECTION_HEADER = "build log review:\n"
# Marker lines as they appear inside the FileList (with newlines).
_BEGIN_LINE = OVERVIEW_BEGIN_MARKER + "\n"
_END_LINE = OVERVIEW_END_MARKER + "\n"


def inject_overview(
    template: MutableSequence[str],
    single_incidents_rows: list[VersionResult],
    aggregated_updates_rows: list[GroupResult],
    build_checks_rows: list[BuildCheckResult],
    *,
    skip_aggregated: bool = False,
) -> bool:
    """Insert (or replace) the openqa_overview block in ``template``.

    Returns ``True`` if the template was modified, ``False`` if the
    template has no ``regression tests:`` section (which means the
    user is exporting against a file that wasn't generated by mtui's
    template machinery and we should leave it alone).

    Marker-bounded: any prior block between ``OVERVIEW_BEGIN_MARKER``
    and ``OVERVIEW_END_MARKER`` is removed before the new one is
    inserted, so re-exports stay idempotent.
    """
    try:
        regression_idx = template.index(_REGRESSION_HEADER)
    except ValueError:
        logger.debug("No 'regression tests:' header found; skipping overview injection")
        return False

    # 1. Strip any previous block, if present.
    _remove_existing_block(template, regression_idx)

    # 2. Find the insertion point: end of the regression-tests section
    #    (after the last non-blank line, before any trailing blanks).
    insert_at = _section_end(template, regression_idx)

    # 2a. Remove the existing trailing blank lines in the section so we
    #     control the gap ourselves. Without this, the block's trailing
    #     `\n` plus the section's existing trailing `\n` would stack.
    trim_end = insert_at
    while trim_end < len(template) and template[trim_end] == "\n":
        trim_end += 1
    if trim_end > insert_at:
        del template[insert_at:trim_end]

    # 3. Build the new block (markers + rendered lines + trailing blank
    #    line for breathing room before the next section).
    rendered = render_overview(
        single_incidents_rows,
        aggregated_updates_rows,
        build_checks_rows,
        skip_aggregated=skip_aggregated,
    )
    block: list[str] = [_BEGIN_LINE]
    block.extend(line + "\n" for line in rendered)
    block.append(_END_LINE)
    block.append("\n")

    # 4. Guarantee one blank line between the prior content (e.g.
    #    "(put your details here)" or user-typed notes) and our block.
    #    `_section_end` strips trailing blanks before the next section,
    #    so without this prefix the block would butt right up against
    #    the previous line.
    if insert_at > 0 and template[insert_at - 1] != "\n":
        block.insert(0, "\n")

    # 5. Splice into the template at the insertion point.
    template[insert_at:insert_at] = block
    return True


def _remove_existing_block(template: MutableSequence[str], search_from: int) -> None:
    """Remove a prior marker-bounded block, if one exists.

    Also strips the single blank line we inserted before the block (if
    any) and the single blank line we appended after it, so repeated
    re-exports do not slowly grow the surrounding gap.
    """
    try:
        begin = template.index(_BEGIN_LINE, search_from)
    except ValueError:
        return
    try:
        end = template.index(_END_LINE, begin)
    except ValueError:
        # Begin without matching end -- corrupt; leave it alone.
        logger.warning(
            "Found %s without matching end marker; not removing", OVERVIEW_BEGIN_MARKER
        )
        return

    end_exclusive = end + 1
    # Swallow the trailing blank line we appended last time.
    if end_exclusive < len(template) and template[end_exclusive] == "\n":
        end_exclusive += 1
    # Swallow the leading blank line we prepended last time, but only
    # if removing it would not glue together the markers with text we
    # do not own (i.e. there is still something non-blank above).
    begin_inclusive = begin
    if (
        begin_inclusive > 0
        and template[begin_inclusive - 1] == "\n"
        and begin_inclusive - 2 >= 0
        and template[begin_inclusive - 2] != "\n"
    ):
        begin_inclusive -= 1
    del template[begin_inclusive:end_exclusive]


def _section_end(template: MutableSequence[str], regression_idx: int) -> int:
    """Find where the regression-tests section ends.

    Returns the index of the next-section header line, or
    ``len(template)`` if there isn't one. The new block is inserted at
    that index, immediately before the next section.
    """
    try:
        next_idx = template.index(_NEXT_SECTION_HEADER, regression_idx + 1)
    except ValueError:
        return len(template)

    # Trim trailing blank lines so we don't sandwich the block between
    # two blank lines on subsequent re-exports.
    while next_idx - 1 > regression_idx and template[next_idx - 1] == "\n":
        next_idx -= 1
    return next_idx
