"""The `show_diff` and `analyze_diff` commands."""

import re
from logging import getLogger

from ..cli.completion import complete_choices, template_completion
from ..cli.term import page
from ..support.misc import requires_update
from . import Command

logger = getLogger("mtui.commands.showdiff")

# A ``source.diff`` generated by OBS/osc is a concatenation of several
# ``header:`` / ``-----`` delimited sections, e.g. ``changes files:``,
# ``old:``, ``new:``, ``spec files:`` and (possibly repeating)
# ``other changes:``.  These are *not* a plain unified diff, so we parse
# them section by section instead of relying on a single marker token.
_SECTION_HEADER = re.compile(r"^([a-z][a-z0-9 ._-]*):\s*$")
_SECTION_UNDERLINE = re.compile(r"^-{3,}\s*$")

# ``+Patch13:        some-fix.patch`` style definitions inside a spec file.
_PATCH_DEF = re.compile(r"^([+-])Patch(\d*):\s+(.*\.patch)\s*$")
# ``+%patch13 -p1`` style application inside a spec file.
_PATCH_APPLY = re.compile(r"^[+-]%patch(\d*)\b")
# ``%autosetup`` / ``%autopatch`` apply patches implicitly.
_AUTOMACRO = re.compile(r"^[+-]?\s*%auto(?:setup|patch)\b")
# Source tarball / archive names listed in ``old:`` / ``new:`` sections.
_ARCHIVE = re.compile(r"\.(?:tar(?:\.\w+)?|tgz|tbz2?|txz|zip|obscpio)\s*$")
# Reviewer-relevant references harvested from changelog text.
_REFERENCE = re.compile(r"\b(?:CVE-\d{4}-\d+|b(?:sc|oo|nc)#\d+|jsc#\w+-\d+)\b")
# Version / global macro bumps worth surfacing.
_VERSION_BUMP = re.compile(
    r"^[+-]\s*(?:Version:|%(?:define|global)\s+\S*ver\w*)\b",
    flags=re.IGNORECASE,
)


def _split_sections(text: str) -> list[tuple[str, list[str]]]:
    """Split a ``source.diff`` into ``(header, body_lines)`` sections.

    A section starts with a ``header:`` line immediately followed by a
    ``-----`` underline.  The body runs until the next such header.  Any
    preamble before the first header is returned under an empty header.
    """
    lines = text.split("\n")
    sections: list[tuple[str, list[str]]] = []
    current_header = ""
    current_body: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        match = _SECTION_HEADER.match(line)
        if match and i + 1 < len(lines) and _SECTION_UNDERLINE.match(lines[i + 1]):
            sections.append((current_header, current_body))
            current_header = match.group(1)
            current_body = []
            i += 2  # skip header + underline
            continue
        current_body.append(line)
        i += 1
    sections.append((current_header, current_body))
    return sections


def _section_bodies(
    sections: list[tuple[str, list[str]]], name: str
) -> list[list[str]]:
    """Return every body whose header matches ``name`` (sections repeat)."""
    return [body for header, body in sections if header == name]


def _defined_patches(spec_lines: list[str]) -> tuple[list[tuple[str, str]], list[str]]:
    """Parse patch definitions from spec section bodies.

    Returns ``(added, removed)`` where ``added`` is a list of
    ``(number, filename)`` for ``+PatchNN:`` lines and ``removed`` is the
    list of filenames from ``-PatchNN:`` lines.
    """
    added: list[tuple[str, str]] = []
    removed: list[str] = []
    for line in spec_lines:
        match = _PATCH_DEF.match(line)
        if not match:
            continue
        sign, number, filename = match.groups()
        if sign == "+":
            added.append((number, filename.strip()))
        else:
            removed.append(filename.strip())
    return added, removed


def _apply_info(spec_lines: list[str]) -> tuple[set[str], bool]:
    """Inspect how patches are applied in the spec section.

    Returns ``(applied_numbers, uses_automacro)``.  ``uses_automacro`` is
    True when ``%autosetup``/``%autopatch`` is present or no ``%patch``
    lines exist at all (kernel-style / implicit application), in which
    case the define-vs-apply cross-check is meaningless.
    """
    applied: set[str] = set()
    uses_automacro = False
    saw_patch_line = False
    for line in spec_lines:
        if _AUTOMACRO.match(line):
            uses_automacro = True
        apply_match = _PATCH_APPLY.match(line)
        if apply_match:
            saw_patch_line = True
            applied.add(apply_match.group(1))
    if not saw_patch_line:
        uses_automacro = True
    return applied, uses_automacro


class ShowDiff(Command):
    """Shows the source diff generated by OBS."""

    command = "show_diff"
    scope = "fanout"

    @classmethod
    def _add_arguments(cls, parser) -> None:
        """Adds arguments to the command's argument parser."""
        cls._add_template_arg(parser)

    @requires_update
    def __call__(self) -> None:
        """Executes the `show_diff` command."""
        diff = self.metadata.report_wd() / "source.diff"
        text = diff.read_text().split("\n")
        page(text, self.prompt.interactive, writer=self.display.println)

    @staticmethod
    def complete(state, text, line, begidx, endidx) -> list[str]:
        """Provides tab completion for the command."""
        return complete_choices(template_completion(state), line, text)


class AnalyzeDiff(Command):
    """Analyzes the OBS source diff to assist with code review."""

    command = "analyze_diff"
    scope = "fanout"

    @classmethod
    def _add_arguments(cls, parser) -> None:
        """Adds arguments to the command's argument parser."""
        cls._add_template_arg(parser)

    @requires_update
    def __call__(self) -> None:
        """Executes the `analyze_diff` command."""
        diff = self.metadata.report_wd() / "source.diff"
        text = diff.read_text()
        sections = _split_sections(text)

        spec_lines = [
            line for body in _section_bodies(sections, "spec files") for line in body
        ]
        if not spec_lines:
            self.prompt.println("No spec mentioned in source.diff")
            return

        changes_lines = [
            line for body in _section_bodies(sections, "changes files") for line in body
        ]
        changes_text = "\n".join(changes_lines)

        added_patches, removed_patches = _defined_patches(spec_lines)
        applied, uses_automacro = _apply_info(spec_lines)

        # Cross-check define vs apply only when it is meaningful.
        if not uses_automacro:
            defined_numbers = {number for number, _ in added_patches}
            if defined_numbers != applied:
                logger.warning(
                    "Patch numbers defined in the spec file (%s) do not match "
                    "the patches applied (%s). Please verify the diff manually.",
                    sorted(defined_numbers) or "none",
                    sorted(applied) or "none",
                )

        # Which added patches are referenced in the changelog?
        mentioned: list[str] = []
        for _, filename in added_patches:
            if re.search(re.escape(filename), changes_text):
                mentioned.append(filename)
            else:
                logger.warning("Patch %s isn't mentioned in any changelog", filename)

        self._print_report(
            sections,
            added_patches,
            removed_patches,
            mentioned,
            uses_automacro,
            changes_text,
        )

    def _print_report(
        self,
        sections: list[tuple[str, list[str]]],
        added_patches: list[tuple[str, str]],
        removed_patches: list[str],
        mentioned: list[str],
        uses_automacro: bool,
        changes_text: str,
    ) -> None:
        """Print a structured, review-friendly summary of the diff."""
        p = self.prompt.println

        p("Source diff analysis:")
        p()

        # Source archives: old -> new.
        old_archives = self._archives(_section_bodies(sections, "old"))
        new_archives = self._archives(_section_bodies(sections, "new"))
        if old_archives or new_archives:
            p("  Source archives:")
            for name in old_archives:
                p(f"    - {name}")
            for name in new_archives:
                p(f"    + {name}")
            p()

        p("  Patches added in spec file:")
        if added_patches:
            for i, (_, filename) in enumerate(added_patches):
                marker = "" if filename in mentioned else "  (not in changelog)"
                p(f"    {i} - {filename}{marker}")
        else:
            p("    (none)")
        p()

        if removed_patches:
            p("  Patches removed from spec file:")
            for i, filename in enumerate(removed_patches):
                p(f"    {i} - {filename}")
            p()

        if uses_automacro:
            p("  Patch application: %autosetup/%autopatch (apply check skipped)")
            p()

        # Version / macro bumps.
        bumps = sorted(
            {
                line.strip()
                for body in _section_bodies(sections, "spec files")
                for line in body
                if _VERSION_BUMP.match(line)
            }
        )
        if bumps:
            p("  Version / macro changes:")
            for line in bumps:
                p(f"    {line}")
            p()

        # Referenced bugs / CVEs from the changelog.
        references = sorted(set(_REFERENCE.findall(changes_text)))
        if references:
            p("  References in changelog:")
            p(f"    {', '.join(references)}")

    @staticmethod
    def _archives(bodies: list[list[str]]) -> list[str]:
        """Collect unique archive filenames from ``old:``/``new:`` bodies."""
        names: list[str] = []
        for body in bodies:
            for line in body:
                candidate = line.strip().lstrip("+-").strip()
                if candidate and _ARCHIVE.search(candidate) and candidate not in names:
                    names.append(candidate)
        return names

    @staticmethod
    def complete(state, text, line, begidx, endidx) -> list[str]:
        """Provides tab completion for the command."""
        return complete_choices(template_completion(state), line, text)
