#!/bin/bash -eu
# oss-fuzz/ClusterFuzzLite build contract: build every cargo-fuzz target and
# place the resulting binaries in $OUT. cargo-fuzz comes preinstalled in the
# base-builder-rust image and picks up fuzz/ automatically.
cargo fuzz build
find fuzz/target/x86_64-unknown-linux-gnu/release -maxdepth 1 -type f -executable ! -name '*.d' -exec cp -t "$OUT" {} +

# Seed corpora. libFuzzer unpacks $OUT/<target>_seed_corpus.zip before a run, so
# each target starts from real parser inputs instead of the single generated byte
# it would otherwise begin from. See fuzz/seed_corpus/README.md.
for dir in fuzz/seed_corpus/*/; do
    target=$(basename "$dir")
    (cd "$dir" && zip -q -r "$OUT/${target}_seed_corpus.zip" .)
done
