[package]
name = "mtui-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
autotests = false

[lints]
workspace = true

[[test]]
name = "it"
path = "tests/it.rs"

[dependencies]
mtui-types.workspace = true
ratatui.workspace = true
ratatui-textarea.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true
