//! Generation helpers for the `xtask gen` task, factored out of `main.rs` so the
//! completion + man-page emission is unit-testable offline (into a `tempdir`)
//! without touching the checked-in `dist/` tree.
//!
//! Both binary parsers derive `clap::Parser`, hence `CommandFactory`, so
//! [`mtui_core::Args::command`] / [`mtui_mcp::McpArgs::command`] hand back the
//! `clap::Command` fed to `clap_complete` and `clap_mangen`. `mtui-mcp` is linked
//! **without** its `mcp` feature: only the (ungated) `args` module is used,
//! keeping the rmcp/axum server graph out of this dev tool's build.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use clap::CommandFactory;
use clap_complete::Shell;

/// The three shells the Phase 8 DoD names explicitly.
pub const SHELLS: [Shell; 3] = [Shell::Bash, Shell::Zsh, Shell::Fish];

/// Fixed column width for rendered command help, so the generated CLI reference
/// is deterministic regardless of the terminal running `xtask` (clap otherwise
/// wraps to the live terminal width).
const CLI_TERM_WIDTH: usize = 80;

/// Generate bash/zsh/fish completions + man pages for **both** binaries into the
/// `dist/` layout rooted at `dist`: `dist/completions/{shell}/…` and
/// `dist/man/<bin>.1`. Creates the directories if missing.
pub fn generate_into(dist: &Path) -> Result<()> {
    let completions = dist.join("completions");
    let man = dist.join("man");
    for shell in SHELLS {
        std::fs::create_dir_all(completions.join(shell.to_string()))
            .with_context(|| format!("creating completions dir for {shell}"))?;
    }
    std::fs::create_dir_all(&man).context("creating man dir")?;

    // `command()` uses the `#[command(name = ...)]` set on each parser, so the
    // generated file names / man titles are already `mtui` and `mtui-mcp`.
    gen_binary(&mut mtui_core::Args::command(), "mtui", &completions, &man)?;
    gen_binary(
        &mut mtui_mcp::McpArgs::command(),
        "mtui-mcp",
        &completions,
        &man,
    )?;
    Ok(())
}

/// Emit the bash/zsh/fish completions and the man page for one binary.
fn gen_binary(cmd: &mut clap::Command, bin: &str, completions: &Path, man: &Path) -> Result<()> {
    for shell in SHELLS {
        clap_complete::generate_to(shell, cmd, bin, completions.join(shell.to_string()))
            .with_context(|| format!("generating {shell} completion for {bin}"))?;
    }
    // Both parsers set `version` AND `long_version` to `MTUI_LONG_VERSION`, a
    // build-provenance string (`<ver> (<sha>-dirty, <profile>, <target>)`). That
    // is right for a live `--version` but poisons a *checked-in* man page (title
    // + VERSION section) with the commit sha / dirty flag / host target, making it
    // churn on every build. mangen renders `long_version` in the VERSION section,
    // so pin *both* to the plain crate version for a stable, committable artifact.
    let stable = cmd
        .clone()
        .version(env!("CARGO_PKG_VERSION"))
        .long_version(env!("CARGO_PKG_VERSION"));
    let page = clap_mangen::Man::new(stable);
    let mut buf = Vec::new();
    page.render(&mut buf)
        .with_context(|| format!("rendering man page for {bin}"))?;
    let man_path = man.join(format!("{bin}.1"));
    std::fs::write(&man_path, &buf).with_context(|| format!("writing {}", man_path.display()))?;
    Ok(())
}

/// The file name of the generated CLI reference under the mdBook `src/` dir.
pub const CLI_REFERENCE_FILE: &str = "cli.md";

/// Render the generated CLI-reference Markdown from the command registry.
///
/// Iterates [`mtui_core::register_all`] in registration order and, for each
/// command, renders a section from its `name`/`aliases`/`about` plus the full
/// long help of the *exact* per-command clap parser [`mtui_core::command_parser`]
/// builds (the same parser real REPL/MCP dispatch uses), so the reference never
/// drifts from the actual arg surface. Deterministic: help is rendered at a
/// fixed [`CLI_TERM_WIDTH`] and the parser version is pinned to the crate
/// version, so the output is stable and committable.
#[must_use]
pub fn render_cli_reference() -> String {
    let registry = mtui_core::register_all();
    let mut out = String::new();
    out.push_str("# Command reference\n\n");
    out.push_str(
        "<!-- GENERATED by `cargo xtask gen-docs` from the mtui command registry. \
         Do not edit by hand; re-run the task to regenerate. -->\n\n",
    );
    out.push_str(
        "Every command below is available in the `mtui` REPL and non-interactive \
         single-command mode. Commands not on the [MCP deny-list](mcp.md) are also \
         exposed as `mtui-mcp` tools. Each command additionally accepts the shared \
         template flags `-T/--template <RRID>` and `--all-templates`.\n\n",
    );

    for name in registry.names() {
        let command = registry
            .get(name)
            .expect("registry.names() yields registered keys");
        write!(out, "## `{name}`\n\n").expect("writing to String cannot fail");

        let aliases = command.aliases();
        if !aliases.is_empty() {
            let joined = aliases
                .iter()
                .map(|a| format!("`{a}`"))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(out, "*Aliases:* {joined}\n").expect("writing to String cannot fail");
        }

        if let Some(about) = command.about() {
            writeln!(out, "{about}\n").expect("writing to String cannot fail");
        }

        // Render the command's *own* argument surface, not the full dispatch
        // parser: `command_parser` also injects the shared base flags
        // (`-T/--template`, `--all-templates`), which some commands legitimately
        // shadow with their own short (`list_refhosts` reuses `-T` for
        // `--testplatform`). clap's `render_long_help` panics on that duplicate
        // short, and the shared flags are already documented once in the preamble
        // above — so build the parser from the command's `configure` alone. Pin
        // version + width so the rendered help is byte-stable across builds and
        // terminals (mirrors the man-page version pin above).
        // No `.version()`: per-command parsers carry no auto `--version` (the
        // engine's dispatch parser doesn't either), and some commands declare
        // their own `--version` arg (`list_refhosts`' SLE-version filter), which
        // would collide with clap's auto flag.
        let base = clap::Command::new(command.name())
            .no_binary_name(true)
            .term_width(CLI_TERM_WIDTH);
        let mut parser = command.configure(base);
        let help = parser.render_long_help();
        out.push_str("```text\n");
        out.push_str(help.to_string().trim_end());
        out.push_str("\n```\n\n");
    }

    // Single trailing newline.
    let trimmed = out.trim_end();
    format!("{trimmed}\n")
}

/// Write the generated CLI reference into the mdBook source dir `src`
/// (`<src>/cli.md`). Creates the directory if missing.
pub fn generate_docs_into(src: &Path) -> Result<()> {
    std::fs::create_dir_all(src).context("creating docs src dir")?;
    let path = src.join(CLI_REFERENCE_FILE);
    std::fs::write(&path, render_cli_reference())
        .with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

// --- Release packaging (`xtask package`) --------------------------------------

/// The two shipped binaries, in `%files` order.
pub const BINARIES: [&str; 2] = ["mtui", "mtui-mcp"];

/// Repo-root files copied verbatim into every release tarball.
const ROOT_FILES: [&str; 2] = ["LICENSE", "README.md"];

/// Inputs for assembling one release-tarball staging tree.
///
/// All paths are taken as-is (no discovery), so the staging assembly is a pure,
/// offline-testable file-copy step: the caller (`run_package`) resolves the real
/// `dist/`, compiled-binary, and repo-root locations from the workspace, while
/// tests point every field at a fixture tempdir.
pub struct PackageInputs<'a> {
    /// Release version string, e.g. `v1.2.0` — names the staging dir + tarball.
    pub version: &'a str,
    /// Rust target triple, e.g. `x86_64-unknown-linux-musl`.
    pub target: &'a str,
    /// Directory holding the freshly built `mtui` / `mtui-mcp` binaries
    /// (`target/<triple>/release`).
    pub bin_dir: &'a Path,
    /// The checked-in `dist/` tree (completions + man + terms).
    pub dist_dir: &'a Path,
    /// Repo root, source of `LICENSE` / `README.md`.
    pub root_dir: &'a Path,
    /// Where the staging dir + tarball are written.
    pub out_dir: &'a Path,
}

/// The base name (no extension) shared by the staging dir and the tarball:
/// `mtui-rs-<version>-<target>`.
#[must_use]
pub fn package_stem(version: &str, target: &str) -> String {
    format!("mtui-rs-{version}-{target}")
}

/// Parsed `package` flags. A tiny hand-rolled parser (no clap in this dev tool),
/// kept in the lib so the flag handling is unit-testable without spawning the
/// `xtask` binary. `--version`/`--target` are required; `--bin-dir`/`--out-dir`
/// override the workspace-relative defaults the caller supplies.
pub struct PackageArgs {
    /// Release version string (`--version`), e.g. `v1.2.0`.
    pub version: String,
    /// Rust target triple (`--target`).
    pub target: String,
    /// Optional override for where the compiled binaries live (`--bin-dir`).
    pub bin_dir: Option<PathBuf>,
    /// Optional override for the tarball output dir (`--out-dir`).
    pub out_dir: Option<PathBuf>,
}

impl PackageArgs {
    /// Parse `package` flags from an arg iterator (already past the task name).
    ///
    /// # Errors
    /// Returns an error on an unknown flag, a flag missing its value, or a
    /// missing required `--version`/`--target`.
    pub fn parse(mut args: impl Iterator<Item = String>) -> Result<Self> {
        let mut version = None;
        let mut target = None;
        let mut bin_dir = None;
        let mut out_dir = None;
        while let Some(flag) = args.next() {
            let mut value = || {
                args.next()
                    .with_context(|| format!("flag {flag} requires a value"))
            };
            match flag.as_str() {
                "--version" => version = Some(value()?),
                "--target" => target = Some(value()?),
                "--bin-dir" => bin_dir = Some(PathBuf::from(value()?)),
                "--out-dir" => out_dir = Some(PathBuf::from(value()?)),
                other => bail!("unknown package flag: {other}"),
            }
        }
        Ok(Self {
            version: version.context("package requires --version")?,
            target: target.context("package requires --target")?,
            bin_dir,
            out_dir,
        })
    }
}

/// Assemble the release staging tree under `<out_dir>/<stem>/` and return its
/// path. Lays out exactly what `docs/src/installation.md` documents installing:
///
/// ```text
/// mtui-rs-<version>-<target>/
///   mtui  mtui-mcp
///   completions/{bash,zsh,fish}/…
///   man/*.1
///   terms/*.sh
///   LICENSE  README.md
/// ```
///
/// Pure file I/O, no subprocess — this is the drift-prone part (must track
/// `dist/`), so it is unit-tested offline against a fixture tree.
pub fn stage_package(inputs: &PackageInputs<'_>) -> Result<PathBuf> {
    let stem = package_stem(inputs.version, inputs.target);
    let staging = inputs.out_dir.join(&stem);
    // Start clean so a re-run is deterministic (mirrors gen idempotency).
    if staging.exists() {
        std::fs::remove_dir_all(&staging)
            .with_context(|| format!("clearing stale staging dir {}", staging.display()))?;
    }
    std::fs::create_dir_all(&staging)
        .with_context(|| format!("creating staging dir {}", staging.display()))?;

    for bin in BINARIES {
        let from = inputs.bin_dir.join(bin);
        let to = staging.join(bin);
        std::fs::copy(&from, &to).with_context(|| format!("copying binary {}", from.display()))?;
        set_executable(&to)?;
    }

    // completions/, man/, terms/ are copied wholesale from dist/ so the tarball
    // never drifts from what `xtask gen` produced.
    copy_dir_all(
        &inputs.dist_dir.join("completions"),
        &staging.join("completions"),
    )
    .context("copying completions/")?;
    copy_dir_all(&inputs.dist_dir.join("man"), &staging.join("man")).context("copying man/")?;
    copy_dir_all(&inputs.dist_dir.join("terms"), &staging.join("terms"))
        .context("copying terms/")?;

    for f in ROOT_FILES {
        let from = inputs.root_dir.join(f);
        std::fs::copy(&from, staging.join(f))
            .with_context(|| format!("copying {}", from.display()))?;
    }

    Ok(staging)
}

/// Assemble + archive one target: stage the tree, `tar czf` it, and write a
/// `<tarball>.sha256`. Returns the tarball path.
///
/// `tar`/`sha256sum` are shelled out (both are present on every CI runner and
/// openSUSE); only the archive/checksum step touches a subprocess — the staging
/// layout it archives is the offline-tested [`stage_package`].
pub fn package_target(inputs: &PackageInputs<'_>) -> Result<PathBuf> {
    // Materialise the staging tree on disk; `tar` archives it by name below.
    stage_package(inputs)?;
    let stem = package_stem(inputs.version, inputs.target);
    let tarball = inputs.out_dir.join(format!("{stem}.tar.gz"));

    // `tar -C <out> <stem>` so the archive holds the versioned top-level dir, not
    // absolute paths.
    run(Command::new("tar")
        .arg("czf")
        .arg(&tarball)
        .arg("-C")
        .arg(inputs.out_dir)
        .arg(&stem))
    .with_context(|| format!("archiving {}", tarball.display()))?;

    write_sha256(&tarball)?;
    Ok(tarball)
}

/// Write `<file>.sha256` next to `file` containing `sha256sum`'s output for it
/// (the `<hash>  <basename>` line, so `sha256sum -c` works from the artifact dir).
fn write_sha256(file: &Path) -> Result<()> {
    let dir = file.parent().context("artifact has no parent dir")?;
    let name = file
        .file_name()
        .context("artifact has no file name")?
        .to_str()
        .context("artifact name is not UTF-8")?;
    let out = Command::new("sha256sum")
        .arg(name)
        .current_dir(dir)
        .output()
        .context("running sha256sum")?;
    if !out.status.success() {
        bail!("sha256sum failed for {}", file.display());
    }
    // Append `.sha256` to the full name (`with_extension` would clobber `.gz`).
    let sum_path = file.with_file_name(format!("{name}.sha256"));
    std::fs::write(&sum_path, &out.stdout)
        .with_context(|| format!("writing {}", sum_path.display()))?;
    Ok(())
}

/// Recursively copy `src` into `dst`, creating `dst` (and parents) as needed.
fn copy_dir_all(src: &Path, dst: &Path) -> Result<()> {
    std::fs::create_dir_all(dst).with_context(|| format!("creating {}", dst.display()))?;
    for entry in std::fs::read_dir(src).with_context(|| format!("reading {}", src.display()))? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let to = dst.join(entry.file_name());
        if ty.is_dir() {
            copy_dir_all(&entry.path(), &to)?;
        } else {
            std::fs::copy(entry.path(), &to)
                .with_context(|| format!("copying {}", entry.path().display()))?;
        }
    }
    Ok(())
}

/// Mark a copied binary executable (0o755) on Unix; a no-op elsewhere. `std::fs::copy`
/// preserves the source mode on Unix, but building via `cross`/CI can leave that
/// mode inconsistent, so set it explicitly.
#[cfg(unix)]
fn set_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt as _;
    let mut perms = std::fs::metadata(path)
        .with_context(|| format!("stat {}", path.display()))?
        .permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(path, perms).with_context(|| format!("chmod {}", path.display()))?;
    Ok(())
}

#[cfg(not(unix))]
fn set_executable(_path: &Path) -> Result<()> {
    Ok(())
}

/// Run a command, failing with its stderr on a non-zero exit.
fn run(cmd: &mut Command) -> Result<()> {
    let out = cmd.output().context("spawning subprocess")?;
    if !out.status.success() {
        bail!(
            "command {:?} failed:\n{}",
            cmd,
            String::from_utf8_lossy(&out.stderr)
        );
    }
    Ok(())
}
