//! Generation helpers for the `xtask gen` task, factored out of `main.rs` so the
//! completion + man-page emission is unit-testable offline (into a `tempdir`)
//! without touching the checked-in `dist/` tree.
//!
//! Both binary parsers derive `clap::Parser`, so
//! [`mtui_core::Args::command`] / [`mtui_mcp::McpArgs::command`] hand back the
//! `clap::Command` fed to `clap_complete` and `clap_mangen`. `mtui-mcp` is linked
//! **without** its `mcp` feature — only the ungated `args` module is used —
//! keeping the rmcp/axum server graph out of this dev tool's build.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use clap::CommandFactory;
use clap_complete::Shell;

/// The three shells the release artefacts cover.
const SHELLS: [Shell; 3] = [Shell::Bash, Shell::Zsh, Shell::Fish];

/// Fixed column width for rendered command help, so the generated CLI reference
/// is deterministic regardless of the terminal running `xtask` (clap otherwise
/// wraps to the live terminal width).
const CLI_TERM_WIDTH: usize = 80;

/// Generate bash/zsh/fish completions + man pages for **both** binaries into the
/// `dist/` layout rooted at `dist`: `dist/completions/{shell}/…` and
/// `dist/man/<bin>.1`. Creates the directories if missing.
pub fn generate_into(dist: &Path) -> Result<()> {
    let completions = dist.join("completions");
    let man = dist.join("man");
    for shell in SHELLS {
        std::fs::create_dir_all(completions.join(shell.to_string()))
            .with_context(|| format!("creating completions dir for {shell}"))?;
    }
    std::fs::create_dir_all(&man).context("creating man dir")?;

    // Each parser's `#[command(name = ...)]` already names the generated files.
    gen_binary(&mut mtui_core::Args::command(), "mtui", &completions, &man)?;
    gen_binary(
        &mut mtui_mcp::McpArgs::command(),
        "mtui-mcp",
        &completions,
        &man,
    )?;
    Ok(())
}

/// Emit the bash/zsh/fish completions and the man page for one binary.
fn gen_binary(cmd: &mut clap::Command, bin: &str, completions: &Path, man: &Path) -> Result<()> {
    for shell in SHELLS {
        clap_complete::generate_to(shell, cmd, bin, completions.join(shell.to_string()))
            .with_context(|| format!("generating {shell} completion for {bin}"))?;
    }
    // Both parsers set `version` and `long_version` to the build-provenance
    // `MTUI_LONG_VERSION` (`<ver> (<sha>-dirty, <profile>, <target>)`), right for
    // a live `--version` but churning a checked-in man page on every build.
    // mangen renders both, so pin both to the plain crate version.
    let stable = cmd
        .clone()
        .version(env!("CARGO_PKG_VERSION"))
        .long_version(env!("CARGO_PKG_VERSION"));
    let page = clap_mangen::Man::new(stable);
    let mut buf = Vec::new();
    page.render(&mut buf)
        .with_context(|| format!("rendering man page for {bin}"))?;
    let man_path = man.join(format!("{bin}.1"));
    std::fs::write(&man_path, &buf).with_context(|| format!("writing {}", man_path.display()))?;
    Ok(())
}

/// The file name of the generated CLI reference under the mdBook `src/` dir.
pub const CLI_REFERENCE_FILE: &str = "cli.md";

/// Render the generated CLI-reference Markdown from the command registry.
///
/// Iterates [`mtui_core::register_all`] in registration order, rendering each
/// command's `name`/`aliases`/`about` plus the long help of the parser real
/// dispatch uses, so the reference cannot drift from the actual arg surface.
/// A fixed `CLI_TERM_WIDTH` and a pinned version keep the output committable.
#[must_use]
pub fn render_cli_reference() -> String {
    let registry = mtui_core::register_all();
    let mut out = String::new();
    out.push_str("# Command reference\n\n");
    out.push_str(
        "<!-- GENERATED by `cargo xtask gen-docs` from the mtui command registry. \
         Do not edit by hand; re-run the task to regenerate. -->\n\n",
    );
    out.push_str(
        "Every command below is available in the `mtui` REPL (see \
         [Invocation](invocation.md) for how to start it and load an update). \
         Commands not on the [MCP deny-list](mcp.md) are also exposed as `mtui-mcp` \
         tools. Each command additionally accepts the shared template flags \
         `-T/--template <RRID>` and `--all-templates`; the cross-command behaviour \
         behind them (fan-out, host-pool selection, locking) is described in \
         [Workflow concepts](concepts.md).\n\n",
    );

    for name in registry.names() {
        let command = registry
            .get(name)
            .expect("registry.names() yields registered keys");
        write!(out, "## `{name}`\n\n").expect("writing to String cannot fail");

        let aliases = command.aliases();
        if !aliases.is_empty() {
            let joined = aliases
                .iter()
                .map(|a| format!("`{a}`"))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(out, "*Aliases:* {joined}\n").expect("writing to String cannot fail");
        }

        if let Some(about) = command.about() {
            writeln!(out, "{about}\n").expect("writing to String cannot fail");
        }

        // The command's *own* surface, not `command_parser`'s: that injects the
        // shared base flags, which a command may legitimately shadow with its own
        // short (`list_refhosts` reuses `-T`), and `render_long_help` panics on
        // the duplicate. The preamble documents the shared flags once instead.
        // No `.version()` either: per-command parsers carry no auto `--version`,
        // and `list_refhosts` declares its own, which would collide.
        let base = clap::Command::new(command.name())
            .no_binary_name(true)
            .term_width(CLI_TERM_WIDTH);
        let mut parser = command.configure(base);
        let help = parser.render_long_help();
        out.push_str("```text\n");
        out.push_str(help.to_string().trim_end());
        out.push_str("\n```\n\n");
    }

    let trimmed = out.trim_end();
    format!("{trimmed}\n")
}

/// The file name of the generated binary-invocation reference under `src/`.
pub const INVOCATION_REFERENCE_FILE: &str = "invocation.md";

/// Render the generated invocation reference (`mtui` + `mtui-mcp` binary flags)
/// from the two top-level clap parsers.
///
/// Where [`render_cli_reference`] documents the REPL *command* surface, this
/// documents how the *binaries* are launched, including that `mtui` is REPL-only
/// (headless single-command dispatch is `mtui-mcp`'s job). Width and version are
/// pinned as in `gen_binary`, so the committed file does not churn.
#[must_use]
pub fn render_invocation_reference() -> String {
    let mut out = String::new();
    out.push_str("# Invocation\n\n");
    out.push_str(
        "<!-- GENERATED by `cargo xtask gen-docs` from the mtui/mtui-mcp clap \
         parsers. Do not edit by hand; re-run the task to regenerate. -->\n\n",
    );
    out.push_str(
        "mtui ships two binaries. `mtui` is the interactive REPL; `mtui-mcp` is \
         the [MCP server](mcp.md). Both read the same [configuration](configuration.md) \
         and accept overrides on the command line.\n\n",
    );
    out.push_str(
        "> **`mtui` is REPL-only.** There is no positional single-command mode: \
         `mtui` always starts the interactive shell (optionally seeding it with \
         `-a`/`-k`/`-s`). Headless, one-shot command dispatch is served by \
         `mtui-mcp`, not by a CLI flag.\n\n",
    );

    render_binary_invocation(&mut out, "mtui", &mut mtui_core::Args::command());
    out.push_str(
        "Loading an update at start with `-a`/`-k` connects its reference hosts and, \
         under the automatic workflow, downloads openQA install logs — the same as \
         running `load_template` in the REPL. `-s`/`--sut` overrides the hosts drawn \
         from the template.\n\n",
    );
    render_binary_invocation(&mut out, "mtui-mcp", &mut mtui_mcp::McpArgs::command());
    out.push_str(
        "`mtui-mcp` takes no boot-time update/host flags (`-a`/`-k`/`-s` are `mtui` \
         only): each MCP client loads its own state at runtime via the \
         `load_template` and `add_host` tools. See [MCP server](mcp.md).\n",
    );

    let trimmed = out.trim_end();
    format!("{trimmed}\n")
}

/// Render one binary's `## <bin>` section: its `about` line and a fenced
/// long-help block. Version + width pinned for a byte-stable committed file.
fn render_binary_invocation(out: &mut String, bin: &str, cmd: &mut clap::Command) {
    write!(out, "## `{bin}`\n\n").expect("writing to String cannot fail");
    let mut stable = cmd
        .clone()
        .version(env!("CARGO_PKG_VERSION"))
        .long_version(env!("CARGO_PKG_VERSION"))
        .term_width(CLI_TERM_WIDTH);
    let help = stable.render_long_help();
    out.push_str("```text\n");
    out.push_str(help.to_string().trim_end());
    out.push_str("\n```\n\n");
}

/// Write the generated CLI + invocation references into the mdBook source dir
/// `src` (`<src>/cli.md`, `<src>/invocation.md`). Creates the directory if
/// missing.
pub fn generate_docs_into(src: &Path) -> Result<()> {
    std::fs::create_dir_all(src).context("creating docs src dir")?;
    let cli = src.join(CLI_REFERENCE_FILE);
    std::fs::write(&cli, render_cli_reference())
        .with_context(|| format!("writing {}", cli.display()))?;
    let invocation = src.join(INVOCATION_REFERENCE_FILE);
    std::fs::write(&invocation, render_invocation_reference())
        .with_context(|| format!("writing {}", invocation.display()))?;
    Ok(())
}

// --- Release packaging (`xtask package`) --------------------------------------

/// The two shipped binaries, in `%files` order.
pub const BINARIES: [&str; 2] = ["mtui", "mtui-mcp"];

/// Repo-root files copied verbatim into every release tarball.
const ROOT_FILES: [&str; 2] = ["LICENSE", "README.md"];

/// Inputs for assembling one release-tarball staging tree.
///
/// All paths are taken as-is, so staging is a pure, offline-testable file copy:
/// `run_package` resolves the real workspace locations, tests point every field
/// at a fixture tempdir.
pub struct PackageInputs<'a> {
    /// Release version string, e.g. `v1.2.0` — names the staging dir + tarball.
    pub version: &'a str,
    /// Rust target triple, e.g. `x86_64-unknown-linux-musl`.
    pub target: &'a str,
    /// Directory holding the freshly built `mtui` / `mtui-mcp` binaries
    /// (`target/<triple>/release`).
    pub bin_dir: &'a Path,
    /// The checked-in `dist/` tree (completions + man + vim-plugin).
    pub dist_dir: &'a Path,
    /// Repo root, source of `LICENSE` / `README.md`.
    pub root_dir: &'a Path,
    /// Where the staging dir + tarball are written.
    pub out_dir: &'a Path,
}

/// The base name (no extension) shared by the staging dir and the tarball:
/// `mtui-<version>-<target>`.
#[must_use]
pub fn package_stem(version: &str, target: &str) -> String {
    format!("mtui-{version}-{target}")
}

/// Parsed `package` flags — hand-rolled (no clap in this dev tool) and kept in
/// the lib so flag handling is testable without spawning the binary.
/// `--version`/`--target` are required; `--bin-dir`/`--out-dir` override the
/// workspace-relative defaults the caller supplies.
pub struct PackageArgs {
    /// Release version string (`--version`), e.g. `v1.2.0`.
    pub version: String,
    /// Rust target triple (`--target`).
    pub target: String,
    /// Optional override for where the compiled binaries live (`--bin-dir`).
    pub bin_dir: Option<PathBuf>,
    /// Optional override for the tarball output dir (`--out-dir`).
    pub out_dir: Option<PathBuf>,
}

impl PackageArgs {
    /// Parse `package` flags from an arg iterator (already past the task name).
    ///
    /// # Errors
    /// Returns an error on an unknown flag, a flag missing its value, or a
    /// missing required `--version`/`--target`.
    pub fn parse(mut args: impl Iterator<Item = String>) -> Result<Self> {
        let mut version = None;
        let mut target = None;
        let mut bin_dir = None;
        let mut out_dir = None;
        while let Some(flag) = args.next() {
            let mut value = || {
                args.next()
                    .with_context(|| format!("flag {flag} requires a value"))
            };
            match flag.as_str() {
                "--version" => version = Some(value()?),
                "--target" => target = Some(value()?),
                "--bin-dir" => bin_dir = Some(PathBuf::from(value()?)),
                "--out-dir" => out_dir = Some(PathBuf::from(value()?)),
                other => bail!("unknown package flag: {other}"),
            }
        }
        Ok(Self {
            version: version.context("package requires --version")?,
            target: target.context("package requires --target")?,
            bin_dir,
            out_dir,
        })
    }
}

/// Assemble the release staging tree under `<out_dir>/<stem>/` and return its
/// path. Lays out exactly what `docs/src/installation.md` documents installing:
///
/// ```text
/// mtui-<version>-<target>/
///   mtui  mtui-mcp
///   completions/{bash,zsh,fish}/…
///   man/*.1
///   vim-plugin/{ftdetect,syntax}/testreport.vim
///   LICENSE  README.md
/// ```
///
/// Pure file I/O, no subprocess — the drift-prone part (it must track `dist/`),
/// so it is unit-tested offline against a fixture tree.
pub fn stage_package(inputs: &PackageInputs<'_>) -> Result<PathBuf> {
    let stem = package_stem(inputs.version, inputs.target);
    let staging = inputs.out_dir.join(&stem);
    // Start clean so a re-run is deterministic.
    if staging.exists() {
        std::fs::remove_dir_all(&staging)
            .with_context(|| format!("clearing stale staging dir {}", staging.display()))?;
    }
    std::fs::create_dir_all(&staging)
        .with_context(|| format!("creating staging dir {}", staging.display()))?;

    for bin in BINARIES {
        let from = inputs.bin_dir.join(bin);
        let to = staging.join(bin);
        std::fs::copy(&from, &to).with_context(|| format!("copying binary {}", from.display()))?;
        set_executable(&to)?;
    }

    // Copied wholesale from dist/ so the tarball cannot drift from `xtask gen`.
    copy_dir_all(
        &inputs.dist_dir.join("completions"),
        &staging.join("completions"),
    )
    .context("copying completions/")?;
    copy_dir_all(&inputs.dist_dir.join("man"), &staging.join("man")).context("copying man/")?;
    copy_dir_all(
        &inputs.dist_dir.join("vim-plugin"),
        &staging.join("vim-plugin"),
    )
    .context("copying vim-plugin/")?;

    for f in ROOT_FILES {
        let from = inputs.root_dir.join(f);
        std::fs::copy(&from, staging.join(f))
            .with_context(|| format!("copying {}", from.display()))?;
    }

    Ok(staging)
}

/// Assemble + archive one target: stage the tree, `tar czf` it, and write a
/// `<tarball>.sha256`. Returns the tarball path.
///
/// `tar` and a SHA-256 CLI are the only subprocesses; the layout they archive is
/// the offline-tested [`stage_package`].
pub fn package_target(inputs: &PackageInputs<'_>) -> Result<PathBuf> {
    let staging = stage_package(inputs)?;
    let stem = package_stem(inputs.version, inputs.target);
    let tarball = inputs.out_dir.join(format!("{stem}.tar.gz"));

    // `-C <out> <stem>` so the archive holds the versioned top-level dir.
    run(Command::new("tar")
        .arg("czf")
        .arg(&tarball)
        .arg("-C")
        .arg(inputs.out_dir)
        .arg(&stem))
    .with_context(|| format!("archiving {}", tarball.display()))?;

    write_sha256(&tarball)?;

    // `out_dir` must hold only the tarball + checksum: release.yml uploads
    // `dist/release/*` verbatim and `gh release create` errors on a directory.
    std::fs::remove_dir_all(&staging)
        .with_context(|| format!("removing staging dir {}", staging.display()))?;

    Ok(tarball)
}

/// Write `<file>.sha256` next to `file` containing the checksum tool's output
/// for it (the `<hash>  <basename>` line, so `sha256sum -c` works from the
/// artifact dir).
fn write_sha256(file: &Path) -> Result<()> {
    let dir = file.parent().context("artifact has no parent dir")?;
    let name = file
        .file_name()
        .context("artifact has no file name")?
        .to_str()
        .context("artifact name is not UTF-8")?;
    let stdout = sha256_stdout(dir, name)?;
    // Append `.sha256` to the full name (`with_extension` would clobber `.gz`).
    let sum_path = file.with_file_name(format!("{name}.sha256"));
    std::fs::write(&sum_path, &stdout)
        .with_context(|| format!("writing {}", sum_path.display()))?;
    Ok(())
}

/// Checksum `name` (relative to `dir`), returning the `<hash>  <name>` stdout.
/// Prefers `sha256sum` (Linux runners) and falls back to macOS's `shasum -a
/// 256`; both emit the same `sha256sum -c`-compatible format.
fn sha256_stdout(dir: &Path, name: &str) -> Result<Vec<u8>> {
    let candidates: [(&str, &[&str]); 2] =
        [("sha256sum", &[name]), ("shasum", &["-a", "256", name])];
    for (prog, args) in candidates {
        if let Some(stdout) = try_sha256_tool(prog, args, dir)? {
            return Ok(stdout);
        }
    }
    bail!("no SHA-256 tool found (tried sha256sum and shasum -a 256)")
}

/// Run a single checksum tool in `dir`. Returns `Ok(Some(stdout))` on success,
/// `Ok(None)` when the tool is not installed (so the caller falls through to the
/// next candidate), and `Err` when it ran but failed on the input or could not
/// be spawned for any other reason.
fn try_sha256_tool(prog: &str, args: &[&str], dir: &Path) -> Result<Option<Vec<u8>>> {
    match Command::new(prog).args(args).current_dir(dir).output() {
        Ok(out) if out.status.success() => Ok(Some(out.stdout)),
        // Present but failed on this input: surface it rather than masking.
        Ok(out) => bail!(
            "{prog} failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ),
        // Not installed: signal the caller to try the next tool.
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(e).with_context(|| format!("running {prog}")),
    }
}

/// Recursively copy `src` into `dst`, creating `dst` (and parents) as needed.
fn copy_dir_all(src: &Path, dst: &Path) -> Result<()> {
    std::fs::create_dir_all(dst).with_context(|| format!("creating {}", dst.display()))?;
    for entry in std::fs::read_dir(src).with_context(|| format!("reading {}", src.display()))? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let to = dst.join(entry.file_name());
        if ty.is_dir() {
            copy_dir_all(&entry.path(), &to)?;
        } else {
            std::fs::copy(entry.path(), &to)
                .with_context(|| format!("copying {}", entry.path().display()))?;
        }
    }
    Ok(())
}

/// Mark a copied binary executable (0o755) on Unix; a no-op elsewhere.
/// `std::fs::copy` preserves the source mode, but a `cross`/CI build can leave
/// that mode inconsistent, so set it explicitly.
#[cfg(unix)]
fn set_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt as _;
    let mut perms = std::fs::metadata(path)
        .with_context(|| format!("stat {}", path.display()))?
        .permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(path, perms).with_context(|| format!("chmod {}", path.display()))?;
    Ok(())
}

#[cfg(not(unix))]
fn set_executable(_path: &Path) -> Result<()> {
    Ok(())
}

/// Run a command, failing with its stderr on a non-zero exit.
fn run(cmd: &mut Command) -> Result<()> {
    let out = cmd.output().context("spawning subprocess")?;
    if !out.status.success() {
        bail!(
            "command {:?} failed:\n{}",
            cmd,
            String::from_utf8_lossy(&out.stderr)
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Whichever tool is on PATH emits `<64-hex>  <name>`; skips cleanly if
    /// neither is installed.
    #[test]
    fn sha256_stdout_emits_hash_and_name() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("f.txt"), b"hello\n").unwrap();
        let out = match sha256_stdout(dir.path(), "f.txt") {
            Ok(o) => o,
            Err(_) => return, // no checksum tool available
        };
        let line = String::from_utf8(out).unwrap();
        assert!(line.contains("f.txt"), "{line:?}");
        assert_eq!(
            line.split_whitespace().next().unwrap().len(),
            64,
            "{line:?}"
        );
    }

    /// A missing tool maps to `Ok(None)` so the caller tries the next candidate.
    #[test]
    fn try_sha256_tool_missing_tool_is_none() {
        let dir = tempfile::tempdir().unwrap();
        let got = try_sha256_tool("mtui-no-such-sha-tool", &["x"], dir.path()).unwrap();
        assert!(got.is_none());
    }

    /// A tool that runs but fails on its input surfaces an error, never masked.
    #[test]
    fn try_sha256_tool_errors_on_bad_input() {
        let dir = tempfile::tempdir().unwrap();
        let candidates: [(&str, &[&str]); 2] = [
            ("sha256sum", &["nope.txt"]),
            ("shasum", &["-a", "256", "nope.txt"]),
        ];
        for (prog, args) in candidates {
            if Command::new(prog).arg("--version").output().is_ok() {
                assert!(
                    try_sha256_tool(prog, args, dir.path()).is_err(),
                    "{prog} should error on a missing file"
                );
                return;
            }
        }
    }
}
