//! Generation helpers for the `xtask gen` task, factored out of `main.rs` so the
//! completion + man-page emission is unit-testable offline (into a `tempdir`)
//! without touching the checked-in `dist/` tree.
//!
//! Both binary parsers derive `clap::Parser`, hence `CommandFactory`, so
//! [`mtui_core::Args::command`] / [`mtui_mcp::McpArgs::command`] hand back the
//! `clap::Command` fed to `clap_complete` and `clap_mangen`. `mtui-mcp` is linked
//! **without** its `mcp` feature: only the (ungated) `args` module is used,
//! keeping the rmcp/axum server graph out of this dev tool's build.

use std::fmt::Write as _;
use std::path::Path;

use anyhow::{Context, Result};
use clap::CommandFactory;
use clap_complete::Shell;

/// The three shells the Phase 8 DoD names explicitly.
pub const SHELLS: [Shell; 3] = [Shell::Bash, Shell::Zsh, Shell::Fish];

/// Fixed column width for rendered command help, so the generated CLI reference
/// is deterministic regardless of the terminal running `xtask` (clap otherwise
/// wraps to the live terminal width).
const CLI_TERM_WIDTH: usize = 80;

/// Generate bash/zsh/fish completions + man pages for **both** binaries into the
/// `dist/` layout rooted at `dist`: `dist/completions/{shell}/…` and
/// `dist/man/<bin>.1`. Creates the directories if missing.
pub fn generate_into(dist: &Path) -> Result<()> {
    let completions = dist.join("completions");
    let man = dist.join("man");
    for shell in SHELLS {
        std::fs::create_dir_all(completions.join(shell.to_string()))
            .with_context(|| format!("creating completions dir for {shell}"))?;
    }
    std::fs::create_dir_all(&man).context("creating man dir")?;

    // `command()` uses the `#[command(name = ...)]` set on each parser, so the
    // generated file names / man titles are already `mtui` and `mtui-mcp`.
    gen_binary(&mut mtui_core::Args::command(), "mtui", &completions, &man)?;
    gen_binary(
        &mut mtui_mcp::McpArgs::command(),
        "mtui-mcp",
        &completions,
        &man,
    )?;
    Ok(())
}

/// Emit the bash/zsh/fish completions and the man page for one binary.
fn gen_binary(cmd: &mut clap::Command, bin: &str, completions: &Path, man: &Path) -> Result<()> {
    for shell in SHELLS {
        clap_complete::generate_to(shell, cmd, bin, completions.join(shell.to_string()))
            .with_context(|| format!("generating {shell} completion for {bin}"))?;
    }
    // Both parsers set `version` AND `long_version` to `MTUI_LONG_VERSION`, a
    // build-provenance string (`<ver> (<sha>-dirty, <profile>, <target>)`). That
    // is right for a live `--version` but poisons a *checked-in* man page (title
    // + VERSION section) with the commit sha / dirty flag / host target, making it
    // churn on every build. mangen renders `long_version` in the VERSION section,
    // so pin *both* to the plain crate version for a stable, committable artifact.
    let stable = cmd
        .clone()
        .version(env!("CARGO_PKG_VERSION"))
        .long_version(env!("CARGO_PKG_VERSION"));
    let page = clap_mangen::Man::new(stable);
    let mut buf = Vec::new();
    page.render(&mut buf)
        .with_context(|| format!("rendering man page for {bin}"))?;
    let man_path = man.join(format!("{bin}.1"));
    std::fs::write(&man_path, &buf).with_context(|| format!("writing {}", man_path.display()))?;
    Ok(())
}

/// The file name of the generated CLI reference under the mdBook `src/` dir.
pub const CLI_REFERENCE_FILE: &str = "cli.md";

/// Render the generated CLI-reference Markdown from the command registry.
///
/// Iterates [`mtui_core::register_all`] in registration order and, for each
/// command, renders a section from its `name`/`aliases`/`about` plus the full
/// long help of the *exact* per-command clap parser [`mtui_core::command_parser`]
/// builds (the same parser real REPL/MCP dispatch uses), so the reference never
/// drifts from the actual arg surface. Deterministic: help is rendered at a
/// fixed [`CLI_TERM_WIDTH`] and the parser version is pinned to the crate
/// version, so the output is stable and committable.
#[must_use]
pub fn render_cli_reference() -> String {
    let registry = mtui_core::register_all();
    let mut out = String::new();
    out.push_str("# Command reference\n\n");
    out.push_str(
        "<!-- GENERATED by `cargo xtask gen-docs` from the mtui command registry. \
         Do not edit by hand; re-run the task to regenerate. -->\n\n",
    );
    out.push_str(
        "Every command below is available in the `mtui` REPL and non-interactive \
         single-command mode. Commands not on the [MCP deny-list](mcp.md) are also \
         exposed as `mtui-mcp` tools. Each command additionally accepts the shared \
         template flags `-T/--template <RRID>` and `--all-templates`.\n\n",
    );

    for name in registry.names() {
        let command = registry
            .get(name)
            .expect("registry.names() yields registered keys");
        write!(out, "## `{name}`\n\n").expect("writing to String cannot fail");

        let aliases = command.aliases();
        if !aliases.is_empty() {
            let joined = aliases
                .iter()
                .map(|a| format!("`{a}`"))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(out, "*Aliases:* {joined}\n").expect("writing to String cannot fail");
        }

        if let Some(about) = command.about() {
            writeln!(out, "{about}\n").expect("writing to String cannot fail");
        }

        // Render the command's *own* argument surface, not the full dispatch
        // parser: `command_parser` also injects the shared base flags
        // (`-T/--template`, `--all-templates`), which some commands legitimately
        // shadow with their own short (`list_refhosts` reuses `-T` for
        // `--testplatform`). clap's `render_long_help` panics on that duplicate
        // short, and the shared flags are already documented once in the preamble
        // above — so build the parser from the command's `configure` alone. Pin
        // version + width so the rendered help is byte-stable across builds and
        // terminals (mirrors the man-page version pin above).
        // No `.version()`: per-command parsers carry no auto `--version` (the
        // engine's dispatch parser doesn't either), and some commands declare
        // their own `--version` arg (`list_refhosts`' SLE-version filter), which
        // would collide with clap's auto flag.
        let base = clap::Command::new(command.name())
            .no_binary_name(true)
            .term_width(CLI_TERM_WIDTH);
        let mut parser = command.configure(base);
        let help = parser.render_long_help();
        out.push_str("```text\n");
        out.push_str(help.to_string().trim_end());
        out.push_str("\n```\n\n");
    }

    // Single trailing newline.
    let trimmed = out.trim_end();
    format!("{trimmed}\n")
}

/// Write the generated CLI reference into the mdBook source dir `src`
/// (`<src>/cli.md`). Creates the directory if missing.
pub fn generate_docs_into(src: &Path) -> Result<()> {
    std::fs::create_dir_all(src).context("creating docs src dir")?;
    let path = src.join(CLI_REFERENCE_FILE);
    std::fs::write(&path, render_cli_reference())
        .with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}
